/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicBithyChatRouteImport } from './routes/api/public/bithy/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBithyChatRoute = ApiPublicBithyChatRouteImport.update({
  id: '/api/public/bithy/chat',
  path: '/api/public/bithy/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/bithy/chat': typeof ApiPublicBithyChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/bithy/chat': typeof ApiPublicBithyChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/bithy/chat': typeof ApiPublicBithyChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/bithy/chat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/bithy/chat'
  id: '__root__' | '/' | '/api/public/bithy/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicBithyChatRoute: typeof ApiPublicBithyChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bithy/chat': {
      id: '/api/public/bithy/chat'
      path: '/api/public/bithy/chat'
      fullPath: '/api/public/bithy/chat'
      preLoaderRoute: typeof ApiPublicBithyChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicBithyChatRoute: ApiPublicBithyChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
