/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedConsoleRouteImport } from './routes/_authenticated/console'
import { Route as AuthenticatedContainertrackRouteImport } from './routes/_authenticated/containertrack'
import { Route as VerifyReportIdRouteImport } from './routes/verify.$reportId'
import { Route as ApiPublicBithyChatRouteImport } from './routes/api/public/bithy/chat'
import { Route as ApiPublicPaymentsPaystackWebhookRouteImport } from './routes/api/public/payments/paystack-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConsoleRoute = AuthenticatedConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContainertrackRoute =
  AuthenticatedContainertrackRouteImport.update({
    id: '/containertrack',
    path: '/containertrack',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const VerifyReportIdRoute = VerifyReportIdRouteImport.update({
  id: '/verify/$reportId',
  path: '/verify/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBithyChatRoute = ApiPublicBithyChatRouteImport.update({
  id: '/api/public/bithy/chat',
  path: '/api/public/bithy/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsPaystackWebhookRoute =
  ApiPublicPaymentsPaystackWebhookRouteImport.update({
    id: '/api/public/payments/paystack-webhook',
    path: '/api/public/payments/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/console': typeof AuthenticatedConsoleRoute
  '/containertrack': typeof AuthenticatedContainertrackRoute
  '/verify/$reportId': typeof VerifyReportIdRoute
  '/api/public/bithy/chat': typeof ApiPublicBithyChatRoute
  '/api/public/payments/paystack-webhook': typeof ApiPublicPaymentsPaystackWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/console': typeof AuthenticatedConsoleRoute
  '/containertrack': typeof AuthenticatedContainertrackRoute
  '/verify/$reportId': typeof VerifyReportIdRoute
  '/api/public/bithy/chat': typeof ApiPublicBithyChatRoute
  '/api/public/payments/paystack-webhook': typeof ApiPublicPaymentsPaystackWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/console': typeof AuthenticatedConsoleRoute
  '/_authenticated/containertrack': typeof AuthenticatedContainertrackRoute
  '/verify/$reportId': typeof VerifyReportIdRoute
  '/api/public/bithy/chat': typeof ApiPublicBithyChatRoute
  '/api/public/payments/paystack-webhook': typeof ApiPublicPaymentsPaystackWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/console'
    | '/containertrack'
    | '/verify/$reportId'
    | '/api/public/bithy/chat'
    | '/api/public/payments/paystack-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/console'
    | '/containertrack'
    | '/verify/$reportId'
    | '/api/public/bithy/chat'
    | '/api/public/payments/paystack-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/console'
    | '/_authenticated/containertrack'
    | '/verify/$reportId'
    | '/api/public/bithy/chat'
    | '/api/public/payments/paystack-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  VerifyReportIdRoute: typeof VerifyReportIdRoute
  ApiPublicBithyChatRoute: typeof ApiPublicBithyChatRoute
  ApiPublicPaymentsPaystackWebhookRoute: typeof ApiPublicPaymentsPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/console': {
      id: '/_authenticated/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof AuthenticatedConsoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/containertrack': {
      id: '/_authenticated/containertrack'
      path: '/containertrack'
      fullPath: '/containertrack'
      preLoaderRoute: typeof AuthenticatedContainertrackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/verify/$reportId': {
      id: '/verify/$reportId'
      path: '/verify/$reportId'
      fullPath: '/verify/$reportId'
      preLoaderRoute: typeof VerifyReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bithy/chat': {
      id: '/api/public/bithy/chat'
      path: '/api/public/bithy/chat'
      fullPath: '/api/public/bithy/chat'
      preLoaderRoute: typeof ApiPublicBithyChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/paystack-webhook': {
      id: '/api/public/payments/paystack-webhook'
      path: '/api/public/payments/paystack-webhook'
      fullPath: '/api/public/payments/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaymentsPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConsoleRoute: typeof AuthenticatedConsoleRoute
  AuthenticatedContainertrackRoute: typeof AuthenticatedContainertrackRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConsoleRoute: AuthenticatedConsoleRoute,
  AuthenticatedContainertrackRoute: AuthenticatedContainertrackRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  VerifyReportIdRoute: VerifyReportIdRoute,
  ApiPublicBithyChatRoute: ApiPublicBithyChatRoute,
  ApiPublicPaymentsPaystackWebhookRoute: ApiPublicPaymentsPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
